ejercicio hecho por rodri y ejercicio2-televisor
Defelippekevin/CFL2021 pull request #6
Opened 2021-07-09 17:59 UTC by Defelippekevin

hice el ejercicio 2 con la clase televisor y decodificador, revísenlo por favor

2021-07-10 00:09 UTC, mauri52 approved these changes

2021-07-11 17:22 UTC, francisco-corti requested changes

2021-07-11 17:22 UTC, francisco-corti commented on modulo3POO/clase25_Encapsulamiento/ejercicioAutomotorLectorArchivos/RegistroAutomotor.ts
> +    }
Acá lo ideal sería recibir la ruta del archivo txt y el separador por parametros, ya sea en este metodo o en el constructor de la clase.
De esta manera logras que la clase sea reutilizable, pudiendo instanciarla N veces leyendo desde diferentes archivos.

2021-07-11 19:07 UTC, francisco-corti approved these changes

2021-07-12 14:44 UTC, mauri52 approved these changes

2021-07-12 19:43 UTC, merged